import React, { useState, useEffect, useMemo } from 'react';
import { Shield, Info, Search, Edit3, Clock, ChevronRight, Filter, FileText, CheckCircle2, AlertCircle, Trash2 } from 'lucide-react';
import styles from './styles/App.module.scss';
import { useStore } from './store/useStore';

const guidelineNames: Record<string, string> = {
  "ALL": "전체 지침",
  "1.1": "1.1 대체 텍스트",
  "1.2": "1.2 자막 제공",
  "2.1.1": "2.1.1 키보드 사용",
  "2.1.3": "2.1.3 조작 가능",
  "2.3.1": "2.3.1 번쩍임 제한",
  "2.4.1": "2.4.1 건너뛰기 링크",
  "2.4.2": "2.4.2 제목 제공",
  "2.4.3": "2.4.3 링크 텍스트"
};

const App = () => {
  const { items, setItems, updateItemStatus, clearItems, projectName } = useStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [judgingId, setJudgingId] = useState<string | null>(null);
  const [tempComment, setTempComment] = useState("");
  const [isConnected, setIsConnected] = useState(false);
  const [activeTab, setActiveTab] = useState("ALL");
  const [copyStatus, setCopyStatus] = useState(false);

  useEffect(() => {
    if ((window as any).electronAPI) {
      const cleanup = (window as any).electronAPI.onUpdateAbtList((data: any) => {
        setIsConnected(true);
        const newItem = {
          ...data,
          id: Math.random().toString(36).substr(2, 9),
          currentStatus: data.result.status,
          finalComment: "",
          history: [{
            timestamp: new Date().toLocaleTimeString(),
            status: data.result.status,
            comment: data.result.message
          }]
        };
        setItems([newItem, ...items]);
      });

      return () => {
        if (typeof cleanup === 'function') cleanup();
      };
    }
  }, [items, setItems]);

  const guidelineTabs = useMemo(() => {
    const ids = Array.from(new Set(items.map(i => i.guideline_id)));
    return ["ALL", ...ids];
  }, [items]);

  const filteredItems = useMemo(() => {
    if (activeTab === "ALL") return items;
    return items.filter(i => i.guideline_id === activeTab);
  }, [items, activeTab]);

  const handleJudge = (id: string, nextStatus: string) => {
    const nextItems = items.map(item => {
      if (item.id === id) {
        return {
          ...item,
          currentStatus: nextStatus,
          finalComment: tempComment,
          history: [...item.history, {
            timestamp: new Date().toLocaleTimeString(),
            status: nextStatus,
            comment: tempComment || "전문가 판정 완료"
          }]
        };
      }
      return item;
    });
    setItems(nextItems);
    setJudgingId(null);
    setTempComment("");
  };

  const generateMarkdownReport = () => {
    const date = new Date().toLocaleDateString();
    let md = `# 🛡️ ABT 접근성 진단 리포트 (${date})\n\n`;
    
    const fails = items.filter(i => i.currentStatus === '오류').length;
    const inapps = items.filter(i => i.currentStatus === '부적절').length;
    const recs = items.filter(i => i.currentStatus === '수정 권고').length;
    
    md += `## 📊 진단 요약\n`;
    md += `- **❌ 오류:** ${fails}건\n`;
    md += `- **🚫 부적절:** ${inapps}건\n`;
    md += `- **⚠️ 수정 권고:** ${recs}건\n\n`;
    md += `---\n\n`;

    const activeGuidelines = Array.from(new Set(items.filter(i => i.currentStatus !== '적절').map(i => i.guideline_id)));
    
    activeGuidelines.forEach(gid => {
      md += `## 📘 ${guidelineNames[gid] || gid}\n\n`;
      const gidItems = items.filter(i => i.guideline_id === gid && i.currentStatus !== '적절');
      
      gidItems.forEach(item => {
        const statusIcon = item.currentStatus === '오류' ? '❌' : item.currentStatus === '부적절' ? '🚫' : '⚠️';
        md += `### ${statusIcon} [${item.currentStatus}] ${item.elementInfo.selector}\n`;
        md += `- **진단 결과:** ${item.result.message}\n`;
        if (item.finalComment) md += `- **QA 전문가 소견:** ${item.finalComment}\n`;
        md += `- **대상 요소:** \`${item.elementInfo.tagName}\`\n`;
        md += `- **주변 맥락:** *"${item.context.smartContext}"*\n\n`;
      });
    });

    md += `---\n*Generated by ABT (A11Y Browser Tester) Desktop*`;
    
    navigator.clipboard.writeText(md).then(() => {
      setCopyStatus(true);
      setTimeout(() => setCopyStatus(false), 2000);
    });
  };

  const selectedItem = items.find(i => i.id === selectedId);

  return (
    <div className={styles.container}>
      <aside className={styles.sidebar} aria-label="프로젝트 내비게이션">
        <header className={styles.header}>
          <div className={styles.brand}>
            <div className={styles.logoBox}>
              <Shield size={20} strokeWidth={2.5} />
            </div>
            <div className={styles.titleGroup}>
              <h1>ABT Engine</h1>
              <span>Desktop Auditor</span>
            </div>
          </div>
        </header>
        
        <nav className={styles.navArea}>
          <h2>검수 세션</h2>
          <ul>
            <li>
              <button className={styles.sessionBtn}>
                <div className={styles.pulse}></div>
                2026-02-20 메인 페이지
              </button>
            </li>
          </ul>
        </nav>

        <footer className={styles.sidebarFooter}>
          <div className={styles.connStatus}>
            <span>Browser Connection</span>
            <div className={`${styles.badge} ${isConnected ? styles.connected : styles.waiting}`}>
              <div className={styles.dot}></div>
              {isConnected ? 'On' : 'Off'}
            </div>
          </div>
        </footer>
      </aside>

      <main className={styles.mainBoard}>
        <header className={styles.topHeader}>
          <div className={styles.headingArea}>
            <h2>{projectName} - 검수 보드</h2>
            <ul className={styles.summaryStats}>
              <li className={styles.failSummary}>오류 {items.filter(i => i.currentStatus === '오류').length}</li>
              <li className={styles.warnSummary}>수정 권고 {items.filter(i => i.currentStatus === '수정 권고').length}</li>
              <li className={styles.reviewSummary}>검토 필요 {items.filter(i => i.currentStatus === '검토 필요').length}</li>
            </ul>
          </div>
          <div className={styles.topActions}>
            <button 
              onClick={clearItems}
              className={styles.clearBtn}
              title="데이터 초기화"
            >
              <Trash2 size={18} />
            </button>
            <button 
              onClick={generateMarkdownReport}
              className={`${styles.reportBtn} ${copyStatus ? styles.copied : styles.ready}`}
            >
              {copyStatus ? <CheckCircle2 size={18} /> : <FileText size={18} />}
              {copyStatus ? "리포트 복사됨!" : "리포트 추출 (Jira용)"}
            </button>
          </div>
        </header>

        <nav className={styles.filterNav}>
          <ul>
            <Filter size={14} className={styles.filterIcon} />
            {guidelineTabs.map(tab => (
              <li key={tab}>
                <button
                  onClick={() => setActiveTab(tab)}
                  className={`${styles.tabBtn} ${activeTab === tab ? styles.active : ''}`}
                >
                  {guidelineNames[tab] || tab}
                  <span className={styles.count}>
                    ({items.filter(i => tab === "ALL" || i.guideline_id === tab).length})
                  </span>
                </button>
              </li>
            ))}
          </ul>
        </nav>

        <section className={`${styles.contentArea} ${styles.customScrollbar}`}>
          {filteredItems.length === 0 ? (
            <div className={styles.emptyState}>
              <Search size={40} />
              <p>No Data Detected</p>
            </div>
          ) : (
            filteredItems.map((item) => (
              <article 
                key={item.id} 
                onClick={() => setSelectedId(item.id)}
                className={`${styles.card} ${selectedId === item.id ? styles.selected : ''}`}
              >
                <div className={styles.cardHeader}>
                  <div className={styles.meta}>
                    <span className={styles.badge}>{guidelineNames[item.guideline_id]?.split(' ')[1] || item.guideline_id}</span>
                    <code>{item.elementInfo?.selector}</code>
                  </div>
                  <div className={`${styles.statusTag} ${
                    item.currentStatus === '오류' ? styles.fail :
                    item.currentStatus === '부적절' ? styles.inappropriate :
                    item.currentStatus === '수정 권고' ? styles.recommendation :
                    item.currentStatus === '검토 필요' ? styles.needs_review :
                    styles.pass
                  }`}>
                    {item.currentStatus === '오류' && <AlertCircle size={12} />}
                    {item.currentStatus}
                  </div>
                </div>
                
                <div className={styles.mainInfo}>
                  <div className={styles.preview}>
                    {item.elementInfo.tagName === 'VIDEO' ? (
                      <div className={styles.videoIcon}>
                        <Clock size={32} />
                        <span>VIDEO</span>
                      </div>
                    ) : (
                      <img src={item.elementInfo?.src} alt="" />
                    )}
                  </div>
                  <div className={styles.textInfo}>
                    <h3>{item.result?.message}</h3>
                    <div className={styles.contextBox}>
                      <h4>Context Analysis</h4>
                      <p>"...{item.context?.smartContext}..."</p>
                    </div>
                    {item.finalComment && (
                      <div className={styles.commentBox}>
                        <h4>Expert Judgement</h4>
                        <p>{item.finalComment}</p>
                      </div>
                    )}
                  </div>
                </div>

                {judgingId === item.id ? (
                  <div className={styles.judgingArea}>
                    <div className={styles.quickChips}>
                      <button onClick={() => setTempComment("주변 정보와 중복되어 장식용 처리를 요청드립니다.")}>#중복정보</button>
                      <button onClick={() => setTempComment("기능형 이미지에 적절한 동작 설명이 포함되어 있습니다.")}>#적절한동작</button>
                      <button onClick={() => setTempComment("불필요한 수식어(사진, 이미지) 삭제를 수정 권고(요청)합니다.")}>#수식어삭제</button>
                    </div>
                    <textarea 
                      value={tempComment}
                      onChange={(e) => setTempComment(e.target.value)}
                      placeholder="개발자에게 전달할 정성 평가 의견을 입력하세요..."
                    />
                    <div className={styles.btnGroup}>
                      <button onClick={() => setJudgingId(null)} className={styles.cancelBtn}>취소</button>
                      <button onClick={() => handleJudge(item.id, '적절')} className={styles.passBtn}>적절함 확인</button>
                      <button onClick={() => handleJudge(item.id, '수정 권고')} className={styles.recomBtn}>개선 권고 요청</button>
                      <button onClick={() => handleJudge(item.id, '부적절')} className={styles.inappBtn}>수정 요청 (부적절)</button>
                    </div>
                  </div>
                ) : (
                  <div className={styles.cardFooter}>
                    <div className={styles.actionGroup}>
                      <button 
                        onClick={(e) => { e.stopPropagation(); setJudgingId(item.id); setTempComment(item.finalComment); }}
                        className={styles.actionBtn}
                      >
                        <Edit3 size={14} /> 수정
                      </button>
                      {item.currentStatus === '검토 필요' && (
                        <button 
                          onClick={(e) => { e.stopPropagation(); handleJudge(item.id, '적절'); }}
                          className={`${styles.actionBtn} ${styles.confirmBtn}`}
                        >
                          <CheckCircle2 size={14} /> 검토 완료
                        </button>
                      )}
                    </div>
                    <div className={styles.timestamp}>
                      <Clock size={12} />
                      <span>Last: {item.currentStatus}</span>
                    </div>
                  </div>
                )}
              </article>
            ))
          )}
        </section>
      </main>

      <aside className={styles.propPanel}>
        <h3><div className={styles.indicator}></div> 상세 속성 및 이력</h3>
        {selectedItem ? (
          <div className={`${styles.propContent} ${styles.customScrollbar}`}>
            <section>
              <h4>Technical Metadata</h4>
              <div className={styles.techMeta}>
                {`<${selectedItem.elementInfo.tagName.toLowerCase()} ...>`}
              </div>
              <div className={styles.tagList}>
                <div className={styles.tagItem}>
                  <label>Tag</label>
                  <span>{selectedItem.elementInfo.tagName}</span>
                </div>
                <div className={styles.tagItem}>
                  <label>ID</label>
                  <span>{selectedItem.guideline_id}</span>
                </div>
              </div>
            </section>
            
            <section>
              <h4>Judgment Timeline</h4>
              <ul className={styles.timeline}>
                {selectedItem.history.map((log: any, i: number) => (
                  <li key={i}>
                    <div className={styles.dot}></div>
                    <time>{log.timestamp}</time>
                    <div className={styles.logStatus}>{log.status}</div>
                    <p className={styles.logComment}>"{log.comment}"</p>
                  </li>
                ))}
              </ul>
            </section>

            <section>
              <h4>Compliance Guide</h4>
              <div className={styles.guideBox}>
                <Info size={20} style={{ flexShrink: 0 }} />
                <p>
                  {selectedItem.guideline_id === '1.1' ? "텍스트가 아닌 콘텐츠에는 그 의미나 용도를 알 수 있도록 대체 텍스트를 제공해야 합니다." : 
                   selectedItem.guideline_id === '1.2' ? "멀티미디어 콘텐츠에는 자막, 대본 또는 수어를 제공해야 합니다." : 
                   "웹 접근성 준수 지침에 따라 적절한 대체 수단을 제공하세요."}
                </p>
              </div>
            </section>
          </div>
        ) : (
          <div className={styles.emptyProp}>
            <ChevronRight size={32} />
            <p>Select an item to view details</p>
          </div>
        )}
      </aside>
    </div>
  );
};

export default App;
